version: '3.4'
name: bookingpro
services:
  bookingpro.api:
    image: ${DOCKER_REGISTRY-}bookingproapi
    build:
      context: .
      dockerfile: BookingPro.API/Dockerfile
    env_file:
      - ./settings.env
    depends_on:
      - bookingpro.database
  bookingpro.database:
    image: postgres:15
    env_file:
      - ./settings.env
    volumes:
      - type: volume
        source: booking-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ../pg_init
        target: /docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  bookingpro.cache.redis:
    image: bitnami/redis:6.2.12
    expose:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - type: volume
        source: redis-data
        target: /bitnami/redis/data
volumes:
  booking-data:
    driver: local
  redis-data:
    driver: local
